# Generated by Django 4.2 on 2023-04-27 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CNH",
            fields=[
                ("numero_cel", models.CharField(max_length=20)),
                ("image", models.ImageField(upload_to="")),
                (
                    "cpf",
                    models.CharField(max_length=14, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(blank=True, max_length=255, null=True)),
                ("documento", models.CharField(blank=True, max_length=75, null=True)),
                (
                    "data_nascimento",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("validade", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "numero_registro",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "data_primeira_habilitacao",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("permissao", models.CharField(blank=True, max_length=15, null=True)),
                ("acc", models.CharField(blank=True, max_length=15, null=True)),
                ("categoria", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "data_emissao",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("local", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DOCCarro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_cel", models.CharField(max_length=20)),
                ("image", models.ImageField(upload_to="")),
                ("cpf_ou_cnpj", models.CharField(blank=True, max_length=20, null=True)),
                ("nome", models.CharField(blank=True, max_length=255, null=True)),
                ("cod_renavam", models.CharField(blank=True, max_length=20, null=True)),
                ("placa", models.CharField(blank=True, max_length=7, null=True)),
                ("exercicio", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "ano_fabricacao",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("ano_modelo", models.CharField(blank=True, max_length=10, null=True)),
                ("numero_crv", models.CharField(blank=True, max_length=25, null=True)),
                ("categoria", models.CharField(blank=True, max_length=155, null=True)),
                ("capacidade", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "potencia_cilindrada",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "peso_bruto_total",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("eixos", models.CharField(blank=True, max_length=25, null=True)),
                ("carroceria", models.CharField(blank=True, max_length=30, null=True)),
                ("cmt", models.CharField(blank=True, max_length=25, null=True)),
                ("lotacao", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "cod_seguranca_cla",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("cat", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "marca_modelo_versão",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                (
                    "especie_tipo",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                (
                    "placa_anterior_uf",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("chassi", models.CharField(blank=True, max_length=75, null=True)),
                (
                    "cor_predominante",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                ("combustivel", models.CharField(blank=True, max_length=75, null=True)),
                ("local", models.CharField(blank=True, max_length=18, null=True)),
                ("data", models.CharField(blank=True, max_length=10, null=True)),
                ("motor", models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DoneOCRQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.IntegerField()),
                ("date_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[("SC", "SUCESS"), ("FL", "FAILED")], max_length=2
                    ),
                ),
                ("number", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="OCRQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="ocrqueue/temp/")),
                ("original_image", models.ImageField(upload_to="ocrqueue/originals/")),
                (
                    "image_type",
                    models.CharField(
                        choices=[("CN", "CNH"), ("DC", "CAR DOC")], max_length=2
                    ),
                ),
                ("number", models.CharField(max_length=20)),
            ],
        ),
    ]
