# Generated by Django 4.2 on 2023-04-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CNH",
            fields=[
                ("image", models.ImageField(upload_to="")),
                (
                    "cpf",
                    models.CharField(max_length=14, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(blank=True, max_length=255, null=True)),
                ("documento", models.CharField(blank=True, max_length=75, null=True)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("validade", models.DateField(blank=True, null=True)),
                (
                    "numero_registro",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("data_primeira_habilitacao", models.DateField(blank=True, null=True)),
                ("permissao", models.CharField(blank=True, max_length=15, null=True)),
                ("acc", models.CharField(blank=True, max_length=15, null=True)),
                ("categoria", models.CharField(blank=True, max_length=3, null=True)),
                ("data_emissao", models.DateField(blank=True, null=True)),
                ("local", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DOCCarro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("cpf_ou_cnpj", models.CharField(blank=True, max_length=20, null=True)),
                ("nome", models.CharField(blank=True, max_length=255, null=True)),
                ("cod_renavam", models.CharField(blank=True, max_length=20, null=True)),
                ("placa", models.CharField(blank=True, max_length=7, null=True)),
                ("exercicio", models.DateField(blank=True, null=True)),
                ("ano_fabricacao", models.DateField(blank=True, null=True)),
                ("ano_modelo", models.DateField(blank=True, null=True)),
                ("numero_crv", models.IntegerField(blank=True, null=True)),
                ("categoria", models.CharField(blank=True, max_length=155, null=True)),
                ("capacidade", models.IntegerField(blank=True, null=True)),
                (
                    "potencia_cilindrada",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("peso_bruto_total", models.FloatField(blank=True, null=True)),
                ("eixos", models.IntegerField(blank=True, null=True)),
                ("carroceria", models.CharField(blank=True, max_length=30, null=True)),
                ("cmt", models.FloatField(blank=True, null=True)),
                ("lotacao", models.CharField(blank=True, max_length=5, null=True)),
                ("cod_seguranca_cla", models.IntegerField(blank=True, null=True)),
                ("cat", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "marca_modelo_versão",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                (
                    "especie_tipo",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                (
                    "placa_anterior_uf",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("chassi", models.CharField(blank=True, max_length=75, null=True)),
                (
                    "cor_predominante",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                ("combustível", models.CharField(blank=True, max_length=75, null=True)),
                ("local", models.CharField(blank=True, max_length=18, null=True)),
                ("data", models.DateField(blank=True, null=True)),
                ("motor", models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="OCRQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="ocrqueue/temp/")),
                ("original_image", models.ImageField(upload_to="ocrqueue/originals/")),
                (
                    "image_type",
                    models.CharField(
                        choices=[("CN", "CNH"), ("DC", "CAR DOC")], max_length=2
                    ),
                ),
            ],
        ),
    ]
