# Generated by Django 4.2 on 2023-04-10 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("motoristas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doccarro",
            old_name="combustível",
            new_name="combustivel",
        ),
    ]
