# Generated by Django 4.2 on 2023-04-28 17:57

from django.db import migrations
import django.utils.timezone
import encrypted_fields.fields


class Migration(migrations.Migration):
    dependencies = [
        ("motoristas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnh",
            name="acc",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cnh",
            name="categoria",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cnh",
            name="data_emissao",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cnh",
            name="data_nascimento",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cnh",
            name="data_primeira_habilitacao",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cnh",
            name="documento",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=75, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cnh",
            name="local",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cnh",
            name="nome",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cnh",
            name="numero_cel",
            field=encrypted_fields.fields.EncryptedCharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="cnh",
            name="numero_registro",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cnh",
            name="permissao",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cnh",
            name="validade",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="ano_fabricacao",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="ano_modelo",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="capacidade",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="carroceria",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="cat",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="categoria",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=155, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="chassi",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=75, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="cmt",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="cod_renavam",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="cod_seguranca_cla",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="combustivel",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=75, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="cor_predominante",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=35, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="cpf_ou_cnpj",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="data",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="eixos",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="especie_tipo",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=75, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="exercicio",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="local",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="lotacao",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="marca_modelo_versão",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=75, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="motor",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="nome",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="numero_cel",
            field=encrypted_fields.fields.EncryptedCharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="numero_crv",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="peso_bruto_total",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="placa",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="placa_anterior_uf",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="potencia_cilindrada",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doneocrqueue",
            name="date_time",
            field=encrypted_fields.fields.EncryptedDateTimeField(
                default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="doneocrqueue",
            name="number",
            field=encrypted_fields.fields.EncryptedCharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="doneocrqueue",
            name="status",
            field=encrypted_fields.fields.EncryptedCharField(
                choices=[("SC", "SUCESS"), ("FL", "FAILED")], max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="ocrqueue",
            name="image_type",
            field=encrypted_fields.fields.EncryptedCharField(
                choices=[("CN", "CNH"), ("DC", "CAR DOC")], max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="ocrqueue",
            name="number",
            field=encrypted_fields.fields.EncryptedCharField(max_length=20),
        ),
    ]
