# Generated by Django 4.2 on 2023-04-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("motoristas", "0002_rename_combustível_doccarro_combustivel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doccarro",
            name="ano_fabricacao",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="ano_modelo",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="capacidade",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="cod_seguranca_cla",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="data",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="eixos",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="exercicio",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="numero_crv",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
