# Generated by Django 4.2 on 2023-04-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("motoristas", "0003_alter_doccarro_ano_fabricacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doccarro",
            name="cmt",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="doccarro",
            name="peso_bruto_total",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
