# Generated by Django 4.2 on 2023-04-11 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("motoristas", "0004_alter_doccarro_cmt_alter_doccarro_peso_bruto_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoneOCRQueue",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "date_time",
                    models.DateTimeField(verbose_name=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SC", "SUCESS"), ("FL", "FAILED")], max_length=2
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="cnh",
            name="data_emissao",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="cnh",
            name="data_nascimento",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="cnh",
            name="data_primeira_habilitacao",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="cnh",
            name="validade",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
