# Generated by Django 4.2 on 2023-04-11 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("motoristas", "0005_doneocrqueue_alter_cnh_data_emissao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doneocrqueue",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
