# Generated by Django 4.2 on 2023-04-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("motoristas", "0006_alter_doneocrqueue_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doneocrqueue",
            name="uuid",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
