# Generated by Django 4.2 on 2023-04-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0007_alter_doneocrqueue_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='doneocrqueue',
            name='number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocrqueue',
            name='number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
